import { useCallback } from "react";
import { useLang } from "@/i18n";

// Words of Shop setup > General and > Website (variations, the editor and the
// style quiz) in the admin app's language. Keyed by the English text, so a
// screen reads naturally (w("Make live")) and anything not listed here shows
// in English. Each entry: [Hinglish, Hindi]; null = same as English.
// {name}-style parts are filled in: w("Edited {date}", { date }).

const D = {
  // ----- Variations screen -----
  "Original website": ["Original website", "मूल वेबसाइट"],
  "Made for your shop. Can't be edited.": ["Aapki dukaan ke liye bani. Badli nahi ja sakti.", "आपकी दुकान के लिए बनी। बदली नहीं जा सकती।"],
  "Edited {date} by {name}": ["{date} ko {name} ne badla", "{date} को {name} ने बदला"],
  "Edited {date}": ["{date} ko badla", "{date} को बदला"],
  "Open {name}": ["{name} kholein", "{name} खोलें"],
  "Live now": ["Abhi live", "अभी लाइव"],
  "This is what customers see when they open your website.": ["Customers aapki website kholne par yahi dekhte hain.", "ग्राहक आपकी वेबसाइट खोलने पर यही देखते हैं।"],
  "Changes you save here show to customers straight away.": ["Yahan save kiye badlav customers ko turant dikhte hain.", "यहाँ सेव किए बदलाव ग्राहकों को तुरंत दिखते हैं।"],
  "Edit": ["Badlein", "बदलें"],
  "Open website": ["Website kholein", "वेबसाइट खोलें"],
  "Only you": ["Sirf aap", "सिर्फ़ आप"],
  "Locked": ["Locked", "लॉक"],
  "Make live": ["Live karein", "लाइव करें"],
  "More": ["Aur", "और"],
  "Preview in new tab": ["Naye tab mein dekhein", "नए टैब में देखें"],
  "Make a copy": ["Copy banayein", "कॉपी बनाएं"],
  "Delete": ["Delete karein", "हटाएं"],
  "Make “{name}” live?": ["“{name}” ko live karein?", "“{name}” को लाइव करें?"],
  "Cancel": ["Cancel", "रद्द करें"],
  "Now:": ["Abhi:", "अभी:"],
  "New:": ["Naya:", "नया:"],
  "Customers will see “{name}” on your website right away.": ["Customers ko aapki website par turant “{name}” dikhega.", "ग्राहकों को आपकी वेबसाइट पर तुरंत “{name}” दिखेगा।"],
  "“{name}” is kept here. You can make it live again any time.": ["“{name}” yahin rahega. Ise kabhi bhi dobara live kar sakte hain.", "“{name}” यहीं रहेगा। इसे कभी भी दोबारा लाइव कर सकते हैं।"],
  "Delete “{name}”?": ["“{name}” delete karein?", "“{name}” हटाएं?"],
  "It is removed for good. This can't be undone.": ["Yeh hamesha ke liye hat jayega. Wapas nahi aayega.", "यह हमेशा के लिए हट जाएगा। वापस नहीं आएगा।"],
  "You already have {n} variations": ["Aapke paas pehle se {n} variations hain", "आपके पास पहले से {n} वेरिएशन हैं"],
  "There's room now": ["Ab jagah hai", "अब जगह है"],
  "Delete one to make room for a new variation.": ["Naye variation ke liye ek delete karein.", "नए वेरिएशन के लिए एक हटाएं।"],
  "You can make your new variation.": ["Ab naya variation bana sakte hain.", "अब नया वेरिएशन बना सकते हैं।"],
  "New variation": ["Naya variation", "नया वेरिएशन"],
  "Live: can't be deleted": ["Live hai: delete nahi ho sakta", "लाइव है: हटा नहीं सकते"],
  "Original: can't be deleted": ["Original hai: delete nahi ho sakta", "मूल है: हटा नहीं सकते"],
  "Only you can see it": ["Sirf aap dekh sakte hain", "सिर्फ़ आप देख सकते हैं"],
  "Delete for good? This can't be undone.": ["Hamesha ke liye delete karein? Wapas nahi aayega.", "हमेशा के लिए हटाएं? वापस नहीं आएगा।"],
  "Keep": ["Rakhein", "रखें"],
  "Variation {n}": ["Variation {n}", "वेरिएशन {n}"],
  "Pick a ready design": ["Taiyaar design chunein", "तैयार डिज़ाइन चुनें"],
  "Choose your kind of shop and a look. Ready words and pictures are filled in, and you can change everything.": ["Apni dukaan ka type aur look chunein. Taiyaar shabd aur tasveerein bhar di jayengi, aap sab badal sakte hain.", "अपनी दुकान का प्रकार और लुक चुनें। तैयार शब्द और तस्वीरें भर दी जाएंगी, आप सब बदल सकते हैं।"],
  "Back": ["Wapas", "वापस"],
  "Make it and start editing": ["Banayein aur badalna shuru karein", "बनाएं और बदलना शुरू करें"],
  "Your kind of shop": ["Aapki dukaan ka type", "आपकी दुकान का प्रकार"],
  "Look": ["Look", "लुक"],
  "Suggested": ["Sujhaya gaya", "सुझाया गया"],
  "Copy a variation": ["Variation copy karein", "वेरिएशन कॉपी करें"],
  "The copy is a draft. The one you copy stays as it is.": ["Copy sirf aapko dikhegi. Asli waisa hi rahega.", "कॉपी सिर्फ़ आपको दिखेगी। असली वैसा ही रहेगा।"],
  "Only you will see it. Your live website stays as it is until you make this one live.": ["Ise sirf aap dekhenge. Jab tak aap ise live nahi karte, aapki live website waisi hi rahegi.", "इसे सिर्फ़ आप देखेंगे। जब तक आप इसे लाइव नहीं करते, आपकी लाइव वेबसाइट वैसी ही रहेगी।"],
  "Answer a few questions": ["Kuch sawaalon ke jawab dein", "कुछ सवालों के जवाब दें"],
  "7 quick taps and we make a design for your shop": ["7 tap mein aapki dukaan ke liye design ban jayega", "7 टैप में आपकी दुकान के लिए डिज़ाइन बन जाएगा"],
  "Easiest": ["Sabse aasaan", "सबसे आसान"],
  "Choose your kind of shop and a look": ["Apni dukaan ka type aur look chunein", "अपनी दुकान का प्रकार और लुक चुनें"],
  "Copy one you already have": ["Pehle wale ki copy banayein", "पहले वाले की कॉपी बनाएं"],
  "Start from one of your variations": ["Apne kisi variation se shuru karein", "अपने किसी वेरिएशन से शुरू करें"],
  "Start empty": ["Khaali se shuru karein", "खाली से शुरू करें"],
  "Just the top bar, a big welcome, your address and the bottom bar. Add the rest yourself.": ["Sirf upar ki patti, bada swagat, aapka pata aur neeche ki patti. Baaki khud jodein.", "सिर्फ़ ऊपर की पट्टी, बड़ा स्वागत, आपका पता और नीचे की पट्टी। बाकी खुद जोड़ें।"],
  "Variation made. Only you can see it.": ["Variation ban gaya. Sirf aap dekh sakte hain.", "वेरिएशन बन गया। सिर्फ़ आप देख सकते हैं।"],
  "Copy made": ["Copy ban gayi", "कॉपी बन गई"],
  "“{name}” is live now": ["“{name}” ab live hai", "“{name}” अब लाइव है"],
  "Deleted": ["Delete ho gaya", "हटा दिया"],
  "Make a variation": ["Variation banayein", "वेरिएशन बनाएं"],
  "A new look for your website": ["Website ka naya look", "वेबसाइट का नया लुक"],
  "Edit and check it": ["Badlein aur dekhein", "बदलें और देखें"],
  "Make it live": ["Live karein", "लाइव करें"],
  "Customers see it right away": ["Customers ko turant dikhega", "ग्राहकों को तुरंत दिखेगा"],
  "Your live website": ["Aapki live website", "आपकी लाइव वेबसाइट"],
  "Other variations": ["Baaki variations", "बाकी वेरिएशन"],
  "{used} of {limit} used": ["{limit} mein se {used} use hue", "{limit} में से {used} इस्तेमाल हुए"],
  "Customers can't see these. Make one live to show it instead.": ["Customers inhe nahi dekh sakte. Dikhane ke liye ek ko live karein.", "ग्राहक इन्हें नहीं देख सकते। दिखाने के लिए एक को लाइव करें।"],
  "All {n} places used. Delete one to add another.": ["Saari {n} jagah bhar gayi. Naya jodne ke liye ek delete karein.", "सारी {n} जगह भर गई। नया जोड़ने के लिए एक हटाएं।"],
  "{n} more allowed": ["{n} aur bana sakte hain", "{n} और बना सकते हैं"],

  // ----- Editor -----
  "Adding photo…": ["Photo jud rahi hai…", "फ़ोटो जुड़ रही है…"],
  "Photo added": ["Photo jud gayi", "फ़ोटो जुड़ गई"],
  "Add photo": ["Photo jodein", "फ़ोटो जोड़ें"],
  "Change photo": ["Photo badlein", "फ़ोटो बदलें"],
  "Add text": ["Likhein", "लिखें"],
  "From your shop details: tap to change": ["Dukaan ki jaankari se: badalne ke liye tap karein", "दुकान की जानकारी से: बदलने के लिए टैप करें"],
  "Move up": ["Upar le jayein", "ऊपर ले जाएं"],
  "Move down": ["Neeche le jayein", "नीचे ले जाएं"],
  "Next layout": ["Agla layout", "अगला लेआउट"],
  "Copy": ["Copy", "कॉपी"],
  "Hide": ["Chhupayein", "छुपाएं"],
  "Show": ["Dikhayein", "दिखाएं"],
  "Add a section from the panel to start.": ["Shuru karne ke liye panel se ek section jodein.", "शुरू करने के लिए पैनल से एक हिस्सा जोड़ें।"],
  "Give this variation a name": ["Is variation ko naam dein", "इस वेरिएशन को नाम दें"],
  "Saved. Customers see the changes now.": ["Save ho gaya. Customers ko badlav ab dikh rahe hain.", "सेव हो गया। ग्राहकों को बदलाव अब दिख रहे हैं।"],
  "Saved. Only you can see it.": ["Save ho gaya. Sirf aap dekh sakte hain.", "सेव हो गया। सिर्फ़ आप देख सकते हैं।"],
  "This variation is live now": ["Yeh variation ab live hai", "यह वेरिएशन अब लाइव है"],
  "You have changes that are not saved. Leave without saving?": ["Kuch badlav save nahi hue. Bina save kiye jayein?", "कुछ बदलाव सेव नहीं हुए। बिना सेव किए जाएं?"],
  "Sections": ["Sections", "हिस्से"],
  "Style": ["Style", "रूप-रंग"],
  "Settings": ["Settings", "सेटिंग"],
  "Close editor": ["Editor band karein", "एडिटर बंद करें"],
  "Live": ["Live", "लाइव"],
  "Draft · only you can see it": ["Draft · sirf aap dekh sakte hain", "ड्राफ़्ट · सिर्फ़ आप देख सकते हैं"],
  "Not saved": ["Save nahi hua", "सेव नहीं हुआ"],
  "Saved": ["Save hai", "सेव है"],
  "Screen size": ["Screen ka size", "स्क्रीन का साइज़"],
  "Computer": ["Computer", "कंप्यूटर"],
  "Tablet": ["Tablet", "टैबलेट"],
  "Phone": ["Phone", "फ़ोन"],
  "Website language": ["Website ki bhasha", "वेबसाइट की भाषा"],
  "Undo": ["Undo", "पहले जैसा करें"],
  "Redo": ["Redo", "फिर से करें"],
  "Earlier saves": ["Pichhle saves", "पिछले सेव"],
  "Open the saved version in a new tab": ["Save kiya hua naye tab mein kholein", "सेव किया हुआ नए टैब में खोलें"],
  "Save and update": ["Save karke update karein", "सेव करके अपडेट करें"],
  "Save": ["Save", "सेव करें"],
  "Preview": ["Dekhein", "देखें"],
  "Tap any text to type, any photo to change it, any section to edit it.": ["Likhne ke liye text par, badalne ke liye photo par, aur badlav ke liye section par tap karein.", "लिखने के लिए टेक्स्ट पर, बदलने के लिए फ़ोटो पर, और बदलाव के लिए हिस्से पर टैप करें।"],
  "Shop details: tap to change them for every variation.": ["Dukaan ki jaankari: tap karke har variation ke liye badlein.", "दुकान की जानकारी: टैप करके हर वेरिएशन के लिए बदलें।"],
  "Edit “{name}”": ["“{name}” badlein", "“{name}” बदलें"],
  "Edit sections, style and settings": ["Sections, style aur settings badlein", "हिस्से, रूप-रंग और सेटिंग बदलें"],
  "Save and make live": ["Save karke live karein", "सेव करके लाइव करें"],
  "Customers will see this variation on your website right away.": ["Customers ko aapki website par turant yeh variation dikhega.", "ग्राहकों को आपकी वेबसाइट पर तुरंत यह वेरिएशन दिखेगा।"],
  "“{name}” is kept. You can make it live again any time.": ["“{name}” rakha rahega. Ise kabhi bhi dobara live kar sakte hain.", "“{name}” रखा रहेगा। इसे कभी भी दोबारा लाइव कर सकते हैं।"],
  "Shop details": ["Dukaan ki jaankari", "दुकान की जानकारी"],
  "“{label}” is part of your shop details. Change it here and every variation, WhatsApp message and the app show the new one.": ["“{label}” aapki dukaan ki jaankari ka hissa hai. Yahan badlein, har variation, WhatsApp message aur app mein naya dikhega.", "“{label}” आपकी दुकान की जानकारी का हिस्सा है। यहाँ बदलें, हर वेरिएशन, WhatsApp मैसेज और ऐप में नया दिखेगा।"],
  "Your page, top to bottom. Tap a section to change it, use the arrows to move it.": ["Aapka page, upar se neeche. Badalne ke liye section par tap karein, hilane ke liye teer use karein.", "आपका पेज, ऊपर से नीचे। बदलने के लिए हिस्से पर टैप करें, खिसकाने के लिए तीर इस्तेमाल करें।"],
  "Hidden from customers": ["Customers se chhupa hai", "ग्राहकों से छुपा है"],
  "Add a section": ["Section jodein", "हिस्सा जोड़ें"],
  "Back to all sections": ["Saare sections par wapas", "सभी हिस्सों पर वापस"],
  "Layout": ["Layout", "लेआउट"],
  "Also shows, from your shop details": ["Dukaan ki jaankari se yeh bhi dikhta hai", "दुकान की जानकारी से यह भी दिखता है"],
  "These are the same in every variation. Tap one to change it.": ["Yeh har variation mein ek jaise hain. Badalne ke liye tap karein.", "ये हर वेरिएशन में एक जैसे हैं। बदलने के लिए टैप करें।"],
  "Background colour": ["Background ka rang", "पीछे का रंग"],
  "Soft colour shapes": ["Halke rangeen aakaar", "हल्के रंगीन आकार"],
  "The blurred colour shapes behind the photo and text": ["Photo aur text ke peeche dhundhle rangeen aakaar", "फ़ोटो और टेक्स्ट के पीछे धुंधले रंगीन आकार"],
  "It goes below the section you have open, or above the bottom bar.": ["Yeh khule section ke neeche, ya neeche ki patti ke upar judega.", "यह खुले हिस्से के नीचे, या नीचे की पट्टी के ऊपर जुड़ेगा।"],
  "Surprise me": ["Kuch naya dikhayein", "कुछ नया दिखाएं"],
  "Ready-made looks": ["Taiyaar looks", "तैयार लुक"],
  "One tap changes colours, letters and shapes together.": ["Ek tap mein rang, akshar aur aakaar sab badal jaate hain.", "एक टैप में रंग, अक्षर और आकार सब बदल जाते हैं।"],
  "Colours": ["Rang", "रंग"],
  "Light": ["Light", "हल्का"],
  "Dark": ["Dark", "गहरा"],
  "Lettering": ["Akshar ka style", "अक्षरों का स्टाइल"],
  "More style choices": ["Aur style options", "और स्टाइल विकल्प"],
  "Corners, buttons, spacing, pattern and movement": ["Kone, buttons, jagah, pattern aur movement", "कोने, बटन, जगह, पैटर्न और हलचल"],
  "Corners": ["Kone", "कोने"],
  "Buttons": ["Buttons", "बटन"],
  "Space between sections": ["Sections ke beech jagah", "हिस्सों के बीच जगह"],
  "Background pattern": ["Background pattern", "पीछे का पैटर्न"],
  "Shows on sections with a coloured background.": ["Rangeen background wale sections par dikhta hai.", "रंगीन पृष्ठभूमि वाले हिस्सों पर दिखता है।"],
  "Movement when scrolling": ["Scroll karne par movement", "स्क्रॉल करने पर हलचल"],
  "Name of this variation": ["Is variation ka naam", "इस वेरिएशन का नाम"],
  "Only you see this name. It helps you tell your variations apart.": ["Yeh naam sirf aap dekhte hain. Variations pehchanne mein madad karta hai.", "यह नाम सिर्फ़ आप देखते हैं। वेरिएशन पहचानने में मदद करता है।"],
  "Quick-contact buttons": ["Turant sampark ke buttons", "तुरंत संपर्क के बटन"],
  "WhatsApp button": ["WhatsApp button", "WhatsApp बटन"],
  "A round green button in the corner of every screen": ["Har screen ke kone mein gol hara button", "हर स्क्रीन के कोने में गोल हरा बटन"],
  "Call bar on phones": ["Phone par call patti", "फ़ोन पर कॉल पट्टी"],
  "Call and Directions buttons fixed at the bottom of phone screens": ["Phone screen ke neeche Call aur Raasta buttons", "फ़ोन स्क्रीन के नीचे कॉल और रास्ता बटन"],
  "Language": ["Bhasha", "भाषा"],
  "English / हिंदी button": ["English / हिंदी button", "English / हिंदी बटन"],
  "Lets customers switch the language at the top of the website": ["Customers website ke upar bhasha badal sakte hain", "ग्राहक वेबसाइट के ऊपर भाषा बदल सकते हैं"],
  "Language customers see first": ["Customers ko pehle kaun si bhasha dikhe", "ग्राहकों को पहले कौन सी भाषा दिखे"],
  "Your website on Google": ["Google par aapki website", "Google पर आपकी वेबसाइट"],
  "How your website shows up when people search on Google.": ["Log Google par search karein to aapki website aise dikhti hai.", "लोग Google पर खोजें तो आपकी वेबसाइट ऐसे दिखती है।"],
  "Google picks a few lines from your page.": ["Google aapke page se kuch lines chunta hai.", "Google आपके पेज से कुछ लाइनें चुनता है।"],
  "Title on Google": ["Google par title", "Google पर शीर्षक"],
  "Empty: your shop name and city.": ["Khaali: dukaan ka naam aur shehar.", "खाली: दुकान का नाम और शहर।"],
  "Line under the title": ["Title ke neeche ki line", "शीर्षक के नीचे की लाइन"],
  "One or two lines about your shop": ["Dukaan ke baare mein ek-do line", "दुकान के बारे में एक-दो लाइन"],
  "Go back to this save? What you have saved now is kept in this list.": ["Is save par wapas jayein? Abhi wala save is list mein rahega.", "इस सेव पर वापस जाएं? अभी वाला सेव इस सूची में रहेगा।"],
  "Brought back": ["Wapas aa gaya", "वापस आ गया"],
  "Each save keeps the one before it (last 15). Bring one back if you change your mind.": ["Har save pichhla save rakhta hai (aakhri 15). Mann badle to wapas laayein.", "हर सेव पिछला सेव रखता है (आखिरी 15)। मन बदले तो वापस लाएं।"],
  "Nothing here yet. Earlier saves show up after you save changes.": ["Abhi kuch nahi. Badlav save karne ke baad pichhle saves dikhenge.", "अभी कुछ नहीं। बदलाव सेव करने के बाद पिछले सेव दिखेंगे।"],
  "{n} sections": ["{n} sections", "{n} हिस्से"],
  "Bring back": ["Wapas laayein", "वापस लाएं"],
  "Plain": ["Saada", "सादा"],
  "Soft colour": ["Halka rang", "हल्का रंग"],
  "Main colour": ["Mukhya rang", "मुख्य रंग"],

  // ----- Fields -----
  "Not added yet, so it is hidden": ["Abhi nahi joda, isliye chhupa hai", "अभी नहीं जोड़ा, इसलिए छुपा है"],
  "Change": ["Badlein", "बदलें"],
  "Add": ["Jodein", "जोड़ें"],
  "shows": ["dikhata hai", "दिखाता है"],
  "Filled in from your shop details.": ["Dukaan ki jaankari se bhara jaata hai.", "दुकान की जानकारी से भरा जाता है।"],
  "Add in {lang}": ["{lang} mein jodein", "{lang} में जोड़ें"],
  "Remove {lang}": ["{lang} hatayein", "{lang} हटाएं"],
  "Remove": ["Hatayein", "हटाएं"],
  "What the button does": ["Button kya karega", "बटन क्या करेगा"],
  "Empty: words that fit the button": ["Khaali: button ke hisaab se shabd", "खाली: बटन के हिसाब से शब्द"],
  "Words on the button": ["Button par shabd", "बटन पर शब्द"],
  "Which section": ["Kaun sa section", "कौन सा हिस्सा"],
  "Choose a section…": ["Section chunein…", "हिस्सा चुनें…"],
  "Link": ["Link", "लिंक"],
  "Not added yet, so this button is hidden": ["Abhi nahi joda, isliye yeh button chhupa hai", "अभी नहीं जोड़ा, इसलिए यह बटन छुपा है"],
  "Icon": ["Icon", "आइकन"],
  "Stars": ["Stars", "स्टार"],
  "Add one more": ["Ek aur jodein", "एक और जोड़ें"],
  "That's the most this section can show.": ["Yeh section isse zyada nahi dikha sakta.", "यह हिस्सा इससे ज़्यादा नहीं दिखा सकता।"],
  "Choose a PNG, JPEG or WebP image": ["PNG, JPEG ya WebP photo chunein", "PNG, JPEG या WebP फ़ोटो चुनें"],
  "Image is too large (max 10 MB)": ["Photo bahut badi hai (10 MB tak)", "फ़ोटो बहुत बड़ी है (10 MB तक)"],

  // ----- General -----
  "Add language": ["Bhasha jodein", "भाषा जोड़ें"],
  "Logo is too large (max 6 MB)": ["Logo bahut bada hai (6 MB tak)", "लोगो बहुत बड़ा है (6 MB तक)"],
  "Logo": ["Logo", "लोगो"],
  "A square picture works best.": ["Chaukor tasveer sabse achhi lagti hai.", "चौकोर तस्वीर सबसे अच्छी लगती है।"],
  "Upload logo": ["Logo upload karein", "लोगो अपलोड करें"],
  "Opening hours are not set, so your website doesn't show them.": ["Khulne ka samay set nahi hai, isliye website par nahi dikhta.", "खुलने का समय सेट नहीं है, इसलिए वेबसाइट पर नहीं दिखता।"],
  "Set opening hours": ["Khulne ka samay set karein", "खुलने का समय सेट करें"],
  "{day} open": ["{day} khula", "{day} खुला"],
  "Closed": ["Band", "बंद"],
  "{day} opens": ["{day} khulta hai", "{day} खुलता है"],
  "to": ["se", "से"],
  "{day} closes": ["{day} band hota hai", "{day} बंद होता है"],
  "Same time every open day": ["Har khule din same samay", "हर खुले दिन एक ही समय"],
  "Don't show hours": ["Samay na dikhayein", "समय न दिखाएं"],
  "Shown as": ["Aise dikhega", "ऐसे दिखेगा"],
  "Optional. Not added.": ["Zaroori nahi. Nahi joda.", "ज़रूरी नहीं। नहीं जोड़ा।"],
  "Not added yet": ["Abhi nahi joda", "अभी नहीं जोड़ा"],
  "Filled in": ["Bhara hua", "भरा हुआ"],
  "Add the pages you have. Their icons show on your website.": ["Jo pages aapke hain, jodein. Unke icon website par dikhenge.", "जो पेज आपके हैं, जोड़ें। उनके आइकन वेबसाइट पर दिखेंगे।"],
  "Shop name is required": ["Dukaan ka naam zaroori hai", "दुकान का नाम ज़रूरी है"],
  "Saved. Your website and app show it now.": ["Save ho gaya. Website aur app mein ab dikh raha hai.", "सेव हो गया। वेबसाइट और ऐप में अब दिख रहा है।"],
  "Name and logo": ["Naam aur logo", "नाम और लोगो"],
  "Logo added": ["Logo juda hai", "लोगो जुड़ा है"],
  "Shop name": ["Dukaan ka naam", "दुकान का नाम"],
  "Shown on your website, the app and the shop screen": ["Website, app aur dukaan ki screen par dikhta hai", "वेबसाइट, ऐप और दुकान की स्क्रीन पर दिखता है"],
  "Short name (optional)": ["Chhota naam (zaroori nahi)", "छोटा नाम (ज़रूरी नहीं)"],
  "Used where space is small, like WhatsApp messages. Empty: the shop name": ["Kam jagah par, jaise WhatsApp messages mein. Khaali: dukaan ka naam", "कम जगह पर, जैसे WhatsApp मैसेज में। खाली: दुकान का नाम"],
  "Firm / Owner name (optional)": ["Firm / Maalik ka naam (zaroori nahi)", "फ़र्म / मालिक का नाम (ज़रूरी नहीं)"],
  "Shown at the bottom of your website": ["Website ke sabse neeche dikhta hai", "वेबसाइट के सबसे नीचे दिखता है"],
  "Add a short name or firm / owner name": ["Chhota naam ya firm / maalik ka naam jodein", "छोटा नाम या फ़र्म / मालिक का नाम जोड़ें"],
  "Address": ["Pata", "पता"],
  "Street address": ["Gali / sadak ka pata", "गली / सड़क का पता"],
  "Shop number, building, street, area and a landmark": ["Dukaan number, building, sadak, ilaka aur koi pehchaan", "दुकान नंबर, बिल्डिंग, सड़क, इलाका और कोई पहचान"],
  "City / town": ["Shehar / kasba", "शहर / कस्बा"],
  "State": ["Rajya", "राज्य"],
  "PIN code": ["PIN code", "पिन कोड"],
  "Country": ["Desh", "देश"],
  "Opening hours": ["Khulne ka samay", "खुलने का समय"],
  "Note about timings (optional)": ["Samay ke baare mein note (zaroori nahi)", "समय के बारे में नोट (ज़रूरी नहीं)"],
  "Like “Open on all festivals” or “Lunch 2–3 PM”": ["Jaise “Sabhi tyohaaron par khula” ya “Lunch 2–3 baje”", "जैसे “सभी त्योहारों पर खुला” या “लंच 2–3 बजे”"],
  "Phone and email": ["Phone aur email", "फ़ोन और ईमेल"],
  "Phone numbers": ["Phone numbers", "फ़ोन नंबर"],
  "The first one is used for the Call button. Up to 4": ["Pehla number Call button ke liye. 4 tak", "पहला नंबर कॉल बटन के लिए। 4 तक"],
  "Add number": ["Number jodein", "नंबर जोड़ें"],
  "WhatsApp number (optional)": ["WhatsApp number (zaroori nahi)", "WhatsApp नंबर (ज़रूरी नहीं)"],
  "Empty: your first phone number is used for WhatsApp": ["Khaali: pehla phone number WhatsApp ke liye use hoga", "खाली: पहला फ़ोन नंबर WhatsApp के लिए इस्तेमाल होगा"],
  "Email (optional)": ["Email (zaroori nahi)", "ईमेल (ज़रूरी नहीं)"],
  "Up to 3. The first one is used for the Email button": ["3 tak. Pehla Email button ke liye", "3 तक। पहला ईमेल बटन के लिए"],
  "Add email": ["Email jodein", "ईमेल जोड़ें"],
  "Google Maps and reviews": ["Google Maps aur reviews", "Google मैप और रिव्यू"],
  "Maps link added": ["Maps link juda hai", "मैप लिंक जुड़ा है"],
  "Reviews link added": ["Reviews link juda hai", "रिव्यू लिंक जुड़ा है"],
  "Google Maps link": ["Google Maps link", "Google मैप लिंक"],
  "Open Google Maps, find your shop, tap Share and copy the link. Empty: directions use your address.": ["Google Maps kholein, apni dukaan dhoondhein, Share dabakar link copy karein. Khaali: raasta aapke pate se.", "Google मैप खोलें, अपनी दुकान ढूंढें, Share दबाकर लिंक कॉपी करें। खाली: रास्ता आपके पते से।"],
  "Google reviews link": ["Google reviews link", "Google रिव्यू लिंक"],
  "From your Google Business Profile: “Ask for reviews”, then copy the link. Empty: the reviews button is hidden.": ["Google Business Profile mein “Ask for reviews” se link copy karein. Khaali: reviews button chhupa rahega.", "Google Business Profile में “Ask for reviews” से लिंक कॉपी करें। खाली: रिव्यू बटन छुपा रहेगा।"],
  "Social media": ["Social media", "सोशल मीडिया"],
  "Your shop's details, kept in one place. Your website, WhatsApp messages and the app all use them.": ["Dukaan ki jaankari, ek jagah. Website, WhatsApp messages aur app sab yahin se lete hain.", "दुकान की जानकारी, एक जगह। वेबसाइट, WhatsApp मैसेज और ऐप सब यहीं से लेते हैं।"],
  "{done} of {all} done": ["{all} mein se {done} poore", "{all} में से {done} पूरे"],
  "You have changes that are not saved": ["Kuch badlav save nahi hue", "कुछ बदलाव सेव नहीं हुए"],
  "Changes show on your website and app at once": ["Badlav website aur app par turant dikhenge", "बदलाव वेबसाइट और ऐप पर तुरंत दिखेंगे"],
  "Other website": ["Doosri website", "दूसरी वेबसाइट"],
  "Website": ["Website", "वेबसाइट"],

  // ----- Shop details (facts) -----
  "Added": ["Juda hai", "जुड़ा है"],
  "your first phone number": ["aapka pehla phone number", "आपका पहला फ़ोन नंबर"],
  "Not added: your address is used": ["Nahi joda: aapka pata use hota hai", "नहीं जोड़ा: आपका पता इस्तेमाल होता है"],
  "Firm / Owner name": ["Firm / Maalik ka naam", "फ़र्म / मालिक का नाम"],
  "WhatsApp number": ["WhatsApp number", "WhatsApp नंबर"],
  "Email": ["Email", "ईमेल"],
  "Social media links": ["Social media links", "सोशल मीडिया लिंक"],

  // ----- Button actions -----
  "Call the shop": ["Dukaan ko call", "दुकान को कॉल"],
  "Directions": ["Raasta", "रास्ता"],
  "Google reviews": ["Google reviews", "Google रिव्यू"],
  "Go to a section": ["Kisi section par jayein", "किसी हिस्से पर जाएं"],
  "Other link": ["Doosra link", "दूसरा लिंक"],
  "No button": ["Koi button nahi", "कोई बटन नहीं"],

  // ----- Sections, their layouts and fields -----
  "Top": ["Upar", "ऊपर"], "Story": ["Kahani", "कहानी"], "Showcase": ["Dikhayein", "दिखाएं"], "Trust": ["Bharosa", "भरोसा"], "Contact": ["Sampark", "संपर्क"],
  "Announcement bar": ["Announcement patti", "सूचना पट्टी"],
  "A thin strip on top for an offer or news": ["Offer ya khabar ke liye upar patli patti", "ऑफ़र या खबर के लिए ऊपर पतली पट्टी"],
  "Bar": ["Patti", "पट्टी"], "Scrolling": ["Chalti hui", "चलती हुई"],
  "Header": ["Upar ki patti", "ऊपर की पट्टी"],
  "Logo, shop name, menu and a main button": ["Logo, dukaan ka naam, menu aur ek button", "लोगो, दुकान का नाम, मेन्यू और एक बटन"],
  "Logo left": ["Logo baayein", "लोगो बाएं"], "Centred": ["Beech mein", "बीच में"], "Split menu": ["Bata hua menu", "बंटा हुआ मेन्यू"], "Minimal": ["Saada", "सादा"],
  "Hero": ["Bada swagat", "बड़ा स्वागत"],
  "The big first impression": ["Pehli nazar ka bada hissa", "पहली नज़र का बड़ा हिस्सा"],
  "Text + photo": ["Text + photo", "टेक्स्ट + फ़ोटो"], "Full photo": ["Poori photo", "पूरी फ़ोटो"], "Collage": ["Collage", "कोलाज"], "Arch frame": ["Mehraab frame", "मेहराब फ़्रेम"], "Poster": ["Poster", "पोस्टर"],
  "About": ["Hamare baare mein", "हमारे बारे में"],
  "Your story, in your words": ["Aapki kahani, aapke shabdon mein", "आपकी कहानी, आपके शब्दों में"],
  "Photo beside": ["Bagal mein photo", "बगल में फ़ोटो"], "Big quote": ["Bada quote", "बड़ा उद्धरण"], "Timeline": ["Samay-rekha", "समय-रेखा"],
  "Why choose us": ["Humein kyun chunein", "हमें क्यों चुनें"],
  "Your strengths, with icons": ["Aapki khoobiyan, icons ke saath", "आपकी खूबियाँ, आइकन के साथ"],
  "Icons": ["Icons", "आइकन"], "Cards": ["Cards", "कार्ड"], "Bento": ["Tiles", "टाइल"], "Checklist": ["Checklist", "चेकलिस्ट"],
  "Products & services": ["Products aur services", "प्रोडक्ट और सेवाएं"],
  "What you sell, with photos and prices": ["Aap kya bechte hain, photo aur daam ke saath", "आप क्या बेचते हैं, फ़ोटो और दाम के साथ"],
  "Arches": ["Mehraab", "मेहराब"], "Side scroll": ["Bagal mein scroll", "बगल में स्क्रॉल"], "Photo tiles": ["Photo tiles", "फ़ोटो टाइल"], "Price list": ["Daam ki list", "दाम की सूची"],
  "Photo gallery": ["Photo gallery", "फ़ोटो गैलरी"],
  "Your shop, products and happy customers": ["Aapki dukaan, products aur khush customers", "आपकी दुकान, प्रोडक्ट और खुश ग्राहक"],
  "Grid": ["Jaali", "ग्रिड"], "Masonry": ["Ooncha-neecha", "ऊँचा-नीचा"], "Mosaic": ["Mosaic", "मोज़ेक"], "Film strip": ["Film patti", "फ़िल्म पट्टी"],
  "Offer": ["Offer", "ऑफ़र"],
  "A sale, coupon or festive deal": ["Sale, coupon ya tyohaar ka offer", "सेल, कूपन या त्योहार का ऑफ़र"],
  "Banner": ["Banner", "बैनर"], "Coupon": ["Coupon", "कूपन"], "With photo": ["Photo ke saath", "फ़ोटो के साथ"],
  "Reviews": ["Reviews", "रिव्यू"],
  "What customers say about you": ["Customers aapke baare mein kya kehte hain", "ग्राहक आपके बारे में क्या कहते हैं"],
  "Spotlight": ["Ek bada review", "एक बड़ा रिव्यू"], "Scrolling wall": ["Chalti deewar", "चलती दीवार"],
  "Numbers": ["Ginti", "गिनती"],
  "Years, customers, products: big numbers": ["Saal, customers, products: bade number", "साल, ग्राहक, प्रोडक्ट: बड़े नंबर"],
  "Row": ["Line", "लाइन"], "Bold band": ["Mota band", "मोटी पट्टी"],
  "Brands": ["Brands", "ब्रांड"],
  "Brands you stock or partners": ["Aapke brands ya partners", "आपके ब्रांड या साथी"],
  "Team": ["Team", "टीम"],
  "The faces behind the counter": ["Counter ke peeche ke chehre", "काउंटर के पीछे के चेहरे"],
  "Circles": ["Gol", "गोल"],
  "Video": ["Video", "वीडियो"],
  "A YouTube video of your shop or products": ["Dukaan ya products ka YouTube video", "दुकान या प्रोडक्ट का YouTube वीडियो"],
  "Wide": ["Chauda", "चौड़ा"], "With text": ["Text ke saath", "टेक्स्ट के साथ"],
  "YouTube link": ["YouTube link", "YouTube लिंक"],
  "Questions": ["Sawaal", "सवाल"],
  "Answers to what people ask most": ["Log sabse zyada jo poochte hain, uske jawaab", "लोग सबसे ज़्यादा जो पूछते हैं, उसके जवाब"],
  "Accordion": ["Khulne wale", "खुलने वाले"], "Two columns": ["Do column", "दो कॉलम"],
  "Text": ["Text", "टेक्स्ट"],
  "A heading and a paragraph": ["Ek heading aur paragraph", "एक शीर्षक और पैराग्राफ़"],
  "Left": ["Baayein", "बाएं"],
  "Call to action": ["Bulawa", "बुलावा"],
  "A bold invitation to call, chat or visit": ["Call, chat ya aane ka bada bulawa", "कॉल, चैट या आने का बड़ा बुलावा"],
  "Band": ["Patti", "पट्टी"], "Card": ["Card", "कार्ड"],
  "Visit us": ["Humse milein", "हमसे मिलें"],
  "Address, hours, map and contact from your shop details": ["Dukaan ki jaankari se pata, samay, map aur sampark", "दुकान की जानकारी से पता, समय, नक्शा और संपर्क"],
  "Map beside": ["Bagal mein map", "बगल में नक्शा"], "Big map": ["Bada map", "बड़ा नक्शा"], "Compact": ["Chhota", "छोटा"],
  "Footer": ["Neeche ki patti", "नीचे की पट्टी"],
  "Name, contact, social links": ["Naam, sampark, social links", "नाम, संपर्क, सोशल लिंक"],
  "Simple": ["Saada", "सादा"], "Columns": ["Columns", "कॉलम"], "Giant name": ["Bada naam", "बड़ा नाम"],
  "Small line above": ["Upar chhoti line", "ऊपर छोटी लाइन"],
  "Heading": ["Heading", "शीर्षक"],
  "Text under heading": ["Heading ke neeche text", "शीर्षक के नीचे टेक्स्ट"],
  "Message": ["Sandesh", "संदेश"],
  "Button": ["Button", "बटन"],
  "Small line under the name": ["Naam ke neeche chhoti line", "नाम के नीचे छोटी लाइन"],
  "Header button": ["Upar ka button", "ऊपर का बटन"],
  "Show menu": ["Menu dikhayein", "मेन्यू दिखाएं"],
  "See-through over the first section": ["Pehle section ke upar paardarshi", "पहले हिस्से के ऊपर पारदर्शी"],
  "Show photo": ["Photo dikhayein", "फ़ोटो दिखाएं"],
  "Main photo": ["Mukhya photo", "मुख्य फ़ोटो"], "Photo 2": ["Photo 2", "फ़ोटो 2"], "Photo 3": ["Photo 3", "फ़ोटो 3"],
  "Main button": ["Mukhya button", "मुख्य बटन"], "Second button": ["Doosra button", "दूसरा बटन"],
  "Show open / closed badge": ["Khula / band ka nishaan dikhayein", "खुला / बंद का निशान दिखाएं"],
  "Show reviews badge": ["Reviews ka nishaan dikhayein", "रिव्यू का निशान दिखाएं"],
  "Photo": ["Photo", "फ़ोटो"], "Signed by": ["Kiski taraf se", "किसकी ओर से"],
  "Milestones": ["Khaas pal", "खास पल"], "Year": ["Saal", "साल"], "What happened": ["Kya hua", "क्या हुआ"],
  "Points": ["Baatein", "बातें"], "Title": ["Title", "शीर्षक"],
  "“Ask on WhatsApp” on each item": ["Har item par “WhatsApp par poochein”", "हर आइटम पर “WhatsApp पर पूछें”"],
  "Items": ["Items", "आइटम"], "Name": ["Naam", "नाम"], "Short note": ["Chhota note", "छोटा नोट"], "Price": ["Daam", "दाम"], "Tag (like New)": ["Tag (jaise New)", "टैग (जैसे नया)"],
  "Photos": ["Photos", "फ़ोटो"], "Caption": ["Caption", "कैप्शन"],
  "Details": ["Details", "जानकारी"], "Coupon code": ["Coupon code", "कूपन कोड"], "Valid till": ["Kab tak", "कब तक"],
  "“See all reviews” button (Google)": ["“Saare reviews dekhein” button (Google)", "“सभी रिव्यू देखें” बटन (Google)"],
  "Review": ["Review", "रिव्यू"], "Place / detail": ["Jagah / jaankari", "जगह / जानकारी"],
  "Heading (optional)": ["Heading (zaroori nahi)", "शीर्षक (ज़रूरी नहीं)"],
  "Number": ["Number", "नंबर"], "Label": ["Label", "लेबल"],
  "People": ["Log", "लोग"], "Role": ["Kaam", "काम"],
  "Question": ["Sawaal", "सवाल"], "Answer": ["Jawaab", "जवाब"],
  "Show map": ["Map dikhayein", "नक्शा दिखाएं"], "Show opening hours": ["Khulne ka samay dikhayein", "खुलने का समय दिखाएं"],
  "Note (like GST number)": ["Note (jaise GST number)", "नोट (जैसे GST नंबर)"],
  "Staff login link": ["Staff login link", "स्टाफ़ लॉगिन लिंक"],
  "Page": ["Page", "पेज"], "Tinted": ["Halka rang", "हल्का रंग"], "Brand": ["Mukhya rang", "मुख्य रंग"],

  // ----- Style choices -----
  "Marigold": ["Genda", "गेंदा"], "Rani pink": ["Rani pink", "रानी गुलाबी"], "Peacock": ["Mor", "मोर"], "Maroon & gold": ["Maroon aur sona", "मैरून और सुनहरा"],
  "Neel": ["Neel", "नील"], "Emerald": ["Panna", "पन्ना"], "Ocean": ["Samundar", "समुंदर"], "Black & gold": ["Kaala aur sona", "काला और सुनहरा"],
  "Lavender": ["Lavender", "लैवेंडर"], "Terracotta": ["Mitti", "मिट्टी"], "Mint fresh": ["Pudina", "पुदीना"], "Haldi": ["Haldi", "हल्दी"],
  "Coral": ["Coral", "मूंगा"], "Ink": ["Syahi", "स्याही"],
  "Modern": ["Modern", "आधुनिक"], "Editorial": ["Akhbaari", "अखबारी"], "Heritage": ["Virasat", "विरासत"], "Friendly": ["Dostana", "दोस्ताना"],
  "Royal": ["Shahi", "शाही"], "Elegant": ["Shaandaar", "शानदार"], "Bold": ["Mota", "मोटा"], "Clean": ["Saaf", "साफ़"],
  "Classic": ["Classic", "क्लासिक"], "Playful": ["Mazedaar", "मज़ेदार"],
  "Sharp": ["Nukeela", "नुकीला"], "Soft": ["Halka gol", "हल्का गोल"], "Round": ["Gol", "गोल"], "Arch": ["Mehraab", "मेहराब"],
  "Solid": ["Bhara", "भरा"], "Pill": ["Gol", "गोल"], "Outline": ["Khaali", "किनारे वाला"], "Pop shadow": ["Parchhai", "परछाई"],
  "Comfortable": ["Theek", "ठीक"], "Airy": ["Khula", "खुला"],
  "None": ["Koi nahi", "कोई नहीं"], "Dots": ["Bindu", "बिंदु"], "Jaali": ["Jaali", "जाली"], "Grain": ["Daanedaar", "दानेदार"], "Waves": ["Lehrein", "लहरें"],
  "Still": ["Ruka", "रुका"], "Subtle": ["Halka", "हल्का"], "Lively": ["Jaandaar", "जानदार"],
  "Festive": ["Tyohaari", "त्योहारी"], "Luxe": ["Shaahi", "शाही"], "Fresh": ["Taaza", "ताज़ा"], "Earthy": ["Mitti jaisa", "मिट्टी जैसा"],

  // ----- Kinds of shop, feels -----
  "Fabric & textiles": ["Kapda", "कपड़ा"], "Clothing & boutique": ["Kapde aur boutique", "कपड़े और बुटीक"], "Sarees & ethnic wear": ["Saree aur ethnic", "साड़ी और पारंपरिक"],
  "Jewellery": ["Jewellery", "ज्वेलरी"], "Salon & beauty": ["Salon aur beauty", "सैलून और ब्यूटी"], "Restaurant & café": ["Restaurant aur café", "रेस्टोरेंट और कैफ़े"],
  "Sweets & bakery": ["Mithai aur bakery", "मिठाई और बेकरी"], "Clinic & doctor": ["Clinic aur doctor", "क्लिनिक और डॉक्टर"], "Mobiles & electronics": ["Mobile aur electronics", "मोबाइल और इलेक्ट्रॉनिक्स"],
  "Furniture & home": ["Furniture aur ghar", "फ़र्नीचर और घर"], "Car & bike showroom": ["Car aur bike showroom", "कार और बाइक शोरूम"], "Gym & fitness": ["Gym aur fitness", "जिम और फ़िटनेस"],
  "Kirana & supermarket": ["Kirana aur supermarket", "किराना और सुपरमार्केट"], "Coaching & services": ["Coaching aur services", "कोचिंग और सेवाएं"],
  "Traditional & warm": ["Paramparik", "पारंपरिक"], "Rich colours, arches, a heritage feel": ["Gehre rang, mehraab, virasat ka ehsaas", "गहरे रंग, मेहराब, विरासत का एहसास"],
  "Modern & clean": ["Modern aur saaf", "आधुनिक और साफ़"], "Crisp, simple, lots of white space": ["Saaf, saada, khuli jagah", "साफ़, सादा, खुली जगह"],
  "Luxury & premium": ["Shaahi aur premium", "शाही और प्रीमियम"], "Dark, elegant, big photos": ["Gehra, shaandaar, badi photos", "गहरा, शानदार, बड़ी फ़ोटो"],
  "Bold & playful": ["Jaandaar aur mazedaar", "जानदार और मज़ेदार"], "Loud colours, big type, energy": ["Tez rang, bade akshar, josh", "तेज़ रंग, बड़े अक्षर, जोश"],

  // ----- Quiz -----
  "Step {i} of {n}": ["{n} mein se step {i}", "{n} में से चरण {i}"],
  "Name this variation": ["Is variation ka naam rakhein", "इस वेरिएशन का नाम रखें"],
  "Try another layout": ["Doosra layout dekhein", "दूसरा लेआउट देखें"],
  "Next": ["Aage", "आगे"],
  "Message on WhatsApp": ["WhatsApp par message", "WhatsApp पर मैसेज"],
  "Best for orders and questions": ["Order aur sawaalon ke liye best", "ऑर्डर और सवालों के लिए सबसे अच्छा"],
  "Best for bookings and quick answers": ["Booking aur jaldi jawaab ke liye best", "बुकिंग और जल्दी जवाब के लिए सबसे अच्छा"],
  "Visit the shop": ["Dukaan par aayein", "दुकान पर आएं"],
  "Best for showrooms and walk-ins": ["Showroom aur seedhe aane walon ke liye best", "शोरूम और सीधे आने वालों के लिए सबसे अच्छा"],
  "What do you sell?": ["Aap kya bechte hain?", "आप क्या बेचते हैं?"],
  "We'll fill your website with the right words. You can change all of it.": ["Hum website mein sahi shabd bhar denge. Aap sab badal sakte hain.", "हम वेबसाइट में सही शब्द भर देंगे। आप सब बदल सकते हैं।"],
  "Which feels most like your shop?": ["Kaun sa aapki dukaan jaisa lagta hai?", "कौन सा आपकी दुकान जैसा लगता है?"],
  "This sets the layout and mood.": ["Isse layout aur mood tay hota hai.", "इससे लेआउट और माहौल तय होता है।"],
  "Pick your colours": ["Apne rang chunein", "अपने रंग चुनें"],
  "Suggested ones first, all of them work.": ["Sujhaye gaye pehle, sab achhe lagte hain.", "सुझाए गए पहले, सब अच्छे लगते हैं।"],
  "Pick your lettering": ["Akshar ka style chunein", "अक्षरों का स्टाइल चुनें"],
  "Shown with your shop name.": ["Aapki dukaan ke naam ke saath dikhaya gaya.", "आपकी दुकान के नाम के साथ दिखाया गया।"],
  "Sharp or soft?": ["Nukeela ya gol?", "नुकीला या गोल?"],
  "The shape of photos, cards and buttons.": ["Photos, cards aur buttons ka aakaar.", "फ़ोटो, कार्ड और बटन का आकार।"],
  "What should visitors do first?": ["Aane wale sabse pehle kya karein?", "आने वाले सबसे पहले क्या करें?"],
  "Your main button and quick-action buttons.": ["Aapka mukhya button aur jaldi wale buttons.", "आपका मुख्य बटन और जल्दी वाले बटन।"],
  "Light or dark?": ["Light ya dark?", "हल्का या गहरा?"],
  "Dark suits luxury and night-time looks.": ["Dark shaahi aur raat wale look par jachta hai.", "गहरा शाही और रात वाले लुक पर जंचता है।"],
  "Here's your new variation": ["Yeh raha aapka naya variation", "यह रहा आपका नया वेरिएशन"],
  "You can change everything next: words, photos, sections and colours.": ["Aage sab badal sakte hain: shabd, photos, sections aur rang.", "आगे सब बदल सकते हैं: शब्द, फ़ोटो, हिस्से और रंग।"],

  // ----- One list, phones, languages, shop details warning -----
  "Customers see this one": ["Customers yahi dekhte hain", "ग्राहक यही देखते हैं"],
  "Link copied": ["Link copy ho gaya", "लिंक कॉपी हो गया"],
  "Please use a computer for this": ["Iske liye computer use karein", "इसके लिए कंप्यूटर इस्तेमाल करें"],
  "OK, got it": ["Theek hai", "ठीक है"],
  "Making a new variation needs a bigger screen, so you can see the whole page while you design it.": ["Naya variation banane ke liye badi screen chahiye, taaki design karte waqt poora page dikhe.", "नया वेरिएशन बनाने के लिए बड़ी स्क्रीन चाहिए, ताकि डिज़ाइन करते समय पूरा पेज दिखे।"],
  "The website editor needs a bigger screen, so you can see the whole page while you change it.": ["Website editor ke liye badi screen chahiye, taaki badalte waqt poora page dikhe.", "वेबसाइट एडिटर के लिए बड़ी स्क्रीन चाहिए, ताकि बदलते समय पूरा पेज दिखे।"],
  "Open this app on a laptop or computer browser (like Chrome), sign in, and go to Shop setup › Website.": ["Yeh app laptop ya computer ke browser (jaise Chrome) mein kholein, login karein, aur Dukaan setup › Website par jayein.", "यह ऐप लैपटॉप या कंप्यूटर के ब्राउज़र (जैसे Chrome) में खोलें, लॉगिन करें, और दुकान सेटअप › वेबसाइट पर जाएं।"],
  "A few quick taps and we make a design for your shop": ["Kuch tap mein aapki dukaan ke liye design ban jayega", "कुछ टैप में आपकी दुकान के लिए डिज़ाइन बन जाएगा"],
  "Your variations": ["Aapke variations", "आपके वेरिएशन"],
  "Customers see only the live one. The others are for you to try ideas.": ["Customers sirf live wala dekhte hain. Baaki aapke naye ideas ke liye hain.", "ग्राहक सिर्फ़ लाइव वाला देखते हैं। बाकी आपके नए आइडिया के लिए हैं।"],
  "Website in English and हिंदी": ["Website English aur हिंदी mein", "वेबसाइट English और हिंदी में"],
  "Every text box gets an “Add in हिंदी” option. Customers can switch between the two.": ["Har text box mein “हिंदी mein jodein” aayega. Customers dono mein badal sakte hain.", "हर टेक्स्ट बॉक्स में “हिंदी में जोड़ें” आएगा। ग्राहक दोनों में बदल सकते हैं।"],
  "Off: your website shows one language, exactly as you write it.": ["Band: website ek hi bhasha mein, jaisa aap likhein.", "बंद: वेबसाइट एक ही भाषा में, जैसा आप लिखें।"],
  "Language button on the website": ["Website par bhasha button", "वेबसाइट पर भाषा बटन"],
  "Shown at the top, so customers can switch": ["Upar dikhta hai, taaki customers bhasha badal sakein", "ऊपर दिखता है, ताकि ग्राहक भाषा बदल सकें"],
  "How the button looks": ["Button kaisa dikhe", "बटन कैसा दिखे"],
  "Two-part switch": ["Do hisson wala switch", "दो हिस्सों वाला स्विच"],
  "Just the word": ["Sirf shabd", "सिर्फ़ शब्द"],
  "Small icon": ["Chhota icon", "छोटा आइकन"],
  "This changes it everywhere": ["Yeh har jagah badlega", "यह हर जगह बदलेगा"],
  "Your shop details are shared. Saving changes them on your live website, in all your variations, in WhatsApp messages and in the app.": ["Dukaan ki jaankari sab jagah ek hai. Save karne par yeh live website, saare variations, WhatsApp messages aur app mein badal jayegi.", "दुकान की जानकारी सब जगह एक है। सेव करने पर यह लाइव वेबसाइट, सभी वेरिएशन, WhatsApp मैसेज और ऐप में बदल जाएगी।"],
  "Go back": ["Wapas", "वापस"],
  "Yes, save everywhere": ["Haan, har jagah save karein", "हाँ, हर जगह सेव करें"],
  "Changes here show everywhere, not just in this variation": ["Yahan ke badlav har jagah dikhenge, sirf is variation mein nahi", "यहाँ के बदलाव हर जगह दिखेंगे, सिर्फ़ इस वेरिएशन में नहीं"],

  // ----- Domain address -----
  "Copied": ["Copy ho gaya", "कॉपी हो गया"],
  "Type": ["Type", "टाइप"],
  "Points to": ["Kahan jaaye", "किस पर जाए"],
  "Get a domain address": ["Domain address lein", "डोमेन पता लें"],
  "Buy one (like myshop.com) from a seller such as GoDaddy, Hostinger or BigRock. Already have one? Skip this.": ["GoDaddy, Hostinger ya BigRock jaise seller se ek khareedein (jaise myshop.com). Pehle se hai? Yeh chhod dein.", "GoDaddy, Hostinger या BigRock जैसे विक्रेता से एक खरीदें (जैसे myshop.com)। पहले से है? यह छोड़ दें।"],
  "Write it here": ["Yahan likhein", "यहाँ लिखें"],
  "Type it in the box and tap Connect.": ["Box mein likhein aur Connect dabayein.", "बॉक्स में लिखें और Connect दबाएं।"],
  "Open its settings": ["Uski settings kholein", "उसकी सेटिंग खोलें"],
  "Sign in where you bought it and open “DNS” or “Manage DNS”.": ["Jahan khareeda wahan login karein aur “DNS” ya “Manage DNS” kholein.", "जहाँ खरीदा वहाँ लॉगिन करें और “DNS” या “Manage DNS” खोलें।"],
  "Add two records": ["Do record jodein", "दो रिकॉर्ड जोड़ें"],
  "Add these two, exactly as shown. If there is already an A record for @ or a record for www, change it to this.": ["Yeh do bilkul aise hi jodein. Agar @ ka A record ya www ka record pehle se hai, to use isse badal dein.", "ये दो बिल्कुल ऐसे ही जोड़ें। अगर @ का A रिकॉर्ड या www का रिकॉर्ड पहले से है, तो उसे इससे बदल दें।"],
  "Wait a little": ["Thoda intezaar karein", "थोड़ा इंतज़ार करें"],
  "It can take a few minutes, sometimes up to a day. Then tap “Check again”.": ["Kuch minute, kabhi ek din tak lag sakta hai. Phir “Dobara check karein” dabayein.", "कुछ मिनट, कभी एक दिन तक लग सकता है। फिर “दोबारा जाँचें” दबाएं।"],
  "Done": ["Ho gaya", "हो गया"],
  "Customers can open your website at your own address. Your current address keeps working too.": ["Customers aapke apne address par website khol sakte hain. Purana address bhi chalta rahega.", "ग्राहक आपके अपने पते पर वेबसाइट खोल सकते हैं। पुराना पता भी चलता रहेगा।"],
  "Use your own domain address": ["Apna domain address lagayein", "अपना डोमेन पता लगाएं"],
  "Your website stays with us. You only point your address here.": ["Website hamare paas hi rahegi. Aap sirf apna address yahan jodte hain.", "वेबसाइट हमारे पास ही रहेगी। आप सिर्फ़ अपना पता यहाँ जोड़ते हैं।"],
  "Saved. Now add the two records where you bought it.": ["Save ho gaya. Ab jahan khareeda wahan do record jodein.", "सेव हो गया। अब जहाँ खरीदा वहाँ दो रिकॉर्ड जोड़ें।"],
  "Removed": ["Hata diya", "हटा दिया"],
  "Domain address": ["Domain address", "डोमेन पता"],
  "Where customers open your website.": ["Customers website kahan kholte hain.", "ग्राहक वेबसाइट कहाँ खोलते हैं।"],
  "Guide": ["Guide", "गाइड"],
  "Included, always on": ["Shaamil, hamesha chalu", "शामिल, हमेशा चालू"],
  "Checking…": ["Check ho raha hai…", "जाँच रहे हैं…"],
  "Connected": ["Jud gaya", "जुड़ गया"],
  "Waiting for setup": ["Setup ka intezaar", "सेटअप का इंतज़ार"],
  "Check again": ["Dobara check karein", "दोबारा जाँचें"],
  "Add these two records where you bought your address:": ["Jahan address khareeda wahan yeh do record jodein:", "जहाँ पता खरीदा वहाँ ये दो रिकॉर्ड जोड़ें:"],
  "Your own domain address (optional)": ["Apna domain address (zaroori nahi)", "अपना डोमेन पता (ज़रूरी नहीं)"],
  "Connect": ["Connect", "जोड़ें"],
  "Have your own address, like myshop.com? Connect it here. Not sure how? Tap Guide.": ["Apna address hai, jaise myshop.com? Yahan jodein. Pata nahi kaise? Guide dabayein.", "अपना पता है, जैसे myshop.com? यहाँ जोड़ें। पता नहीं कैसे? गाइड दबाएं।"],

  // ----- Quiz: layout and language -----
  "One language": ["Ek bhasha", "एक भाषा"],
  "Simple. Your website shows exactly what you write.": ["Saada. Website wahi dikhati hai jo aap likhte hain.", "सादा। वेबसाइट वही दिखाती है जो आप लिखते हैं।"],
  "English and हिंदी": ["English aur हिंदी", "English और हिंदी"],
  "Customers can switch. You add हिंदी text to each part.": ["Customers bhasha badal sakte hain. Aap har hisse mein हिंदी text jodte hain.", "ग्राहक भाषा बदल सकते हैं। आप हर हिस्से में हिंदी टेक्स्ट जोड़ते हैं।"],
  "This sets the mood of the whole page.": ["Isse poore page ka mood tay hota hai.", "इससे पूरे पेज का माहौल तय होता है।"],
  "How should the top of your website look?": ["Website ka upar wala hissa kaisa dikhe?", "वेबसाइट का ऊपर वाला हिस्सा कैसा दिखे?"],
  "The first thing customers see. Suggested one is marked.": ["Customers sabse pehle yahi dekhte hain. Sujhaya gaya marked hai.", "ग्राहक सबसे पहले यही देखते हैं। सुझाया गया चिह्नित है।"],
  "One language or two?": ["Ek bhasha ya do?", "एक भाषा या दो?"],
  "You can change this later in Settings.": ["Ise baad mein Settings mein badal sakte hain.", "इसे बाद में सेटिंग में बदल सकते हैं।"],

  // ----- Compact list, phone note, guide -----
  "Open": ["Kholein", "खोलें"],
  "Original design": ["Original design", "मूल डिज़ाइन"],
  "OK": ["Theek hai", "ठीक है"],
  "Please use a computer or laptop": ["Computer ya laptop use karein", "कंप्यूटर या लैपटॉप इस्तेमाल करें"],
  "This feature works on a bigger screen.": ["Yeh feature badi screen par chalta hai.", "यह सुविधा बड़ी स्क्रीन पर चलती है।"],
  "To design or edit your website, please use a computer or laptop.": ["Website design ya edit karne ke liye computer ya laptop use karein.", "वेबसाइट डिज़ाइन या बदलने के लिए कंप्यूटर या लैपटॉप इस्तेमाल करें।"],
  "How to connect your own domain address": ["Apna domain address kaise jodein", "अपना डोमेन पता कैसे जोड़ें"],
  "Step-by-step guide, takes 5 minutes": ["Step-by-step guide, 5 minute lagenge", "आसान गाइड, 5 मिनट लगेंगे"],
  "Open guide": ["Guide kholein", "गाइड खोलें"],

  // ----- Days -----
  "Mon": ["Som", "सोम"], "Tue": ["Mangal", "मंगल"], "Wed": ["Budh", "बुध"], "Thu": ["Guru", "गुरु"], "Fri": ["Shukra", "शुक्र"], "Sat": ["Shani", "शनि"], "Sun": ["Ravi", "रवि"],
};

const COL = { hinglish: 0, hindi: 1 };

export function translate(lang, text, vars) {
  const row = D[text];
  const col = COL[lang];
  let out = (row && col !== undefined && row[col]) || text;
  if (vars) out = out.replace(/\{(\w+)\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
  return out;
}

// w("Make live") / w("Edited {date}", { date }) in the admin app's language.
export function useW() {
  const ctx = useLang();
  const lang = ctx ? ctx.lang : "english";
  return useCallback((text, vars) => translate(lang, text, vars), [lang]);
}
